### ISSUE TITLE
Copy in the README not appearing in Learn

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#1]
Copy in sections three and four is in the README on Github, but is not appearing in Learn.

Github:

![00000044](https://cloud.githubusercontent.com/assets/2243896/7775083/f306153c-007d-11e5-876c-40330d20db2b.png)

Learn:

![00000045](https://cloud.githubusercontent.com/assets/2243896/7775094/0eb164da-007e-11e5-92c8-b9703d844ab5.png)

**Comment by markedwardmurray** [comment]
@SophieDeBenedetto: It looks like the canonical needs to redeployed. The learn-co-students repo has 9 of the 13 commits.
