### ISSUE TITLE
New users will not know how to run program

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#14]
The readme contains the following instruction: 

To run the program from the root of this lab's directory type: `ruby lib/a_ruby_program.rb.`

However, in order to open it the user would have to fork & clone. We have not yet told users how to do this. And because it is a readme, the "Open" button will not be available. 

Suggest removing instruction. 

cc @AnnJohn

**Comment by matbalez-zz** [comment]
And later in the content, we should change the grammar to something like "If you were to run this lab..." rather than "If you run this lab..."

**Comment by aviflombaum** [comment]
Tried addressing these in 65a07af
