### ISSUE TITLE
Ruby Lecture Intro (What is A Program) — Broken Link

### ISSUE THREAD

**Issue by yancann** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#16]
The Source Code link for download leads to a 404 in Git.

https://github.com/learn-co-students/ruby-lecture-intro-what-is-a-program-q-000/archive/1.0.0.zip

**Comment by aviflombaum** [comment]
Thanks for report - I fixed it for this lab and we'll be fixing these sort of links for all labs in the future. Sorry!!!
