### ISSUE TITLE
Issue with Lessons Appearing complete

### ISSUE THREAD

**Issue by amyewitt** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#20]
I am having two issues with lessons appearing complete
1) Ruby Lecture Intro - I completed the reading but when I click next lesson it says that I have not finished the lesson (it's only a readme)
2) Hello World Ruby - I completed the lab and submitted but it is not a filled in green circle on the left

![screen shot 2015-10-16 at 8 03 05 pm](https://cloud.githubusercontent.com/assets/14812446/10556731/23863a7a-7441-11e5-98cb-08c488439a39.png)
![screen shot 2015-10-16 at 8 03 20 pm](https://cloud.githubusercontent.com/assets/14812446/10556730/2385fe20-7441-11e5-8be2-7a77beda5198.png)

**Comment by amyewitt** [comment]
The IRB lesson is showing as complete now but the 'Intro to program' is still showing as incomplete - that is especially because it's just a README

**Comment by amyewitt** [comment]
Is this the wrong platform for this?

**Comment by dfenjves** [comment]
Hi @amyewitt, for bugs like this it's best to reach out on the learn-co-issues channel on slack or the "submit a bug" button on the bottom left of learn.co. I'll pass this on though - @loganhasson, can you take a look?

**Comment by loganhasson** [comment]
@dfenjves will take a peek mañana. seems like a bad data thing on our end.

**Comment by amyewitt** [comment]
I'm not sure why this was closed. The issue has not been resolved.

**Comment by AnnJohn** [comment]
Hi @amyewitt we closed this issue because it is an engineering issue and not directly related to curriculum content. We resolved a lot of the problems with the lights, but if this is still an issue, please use the "submit a bug" button or the "Ask a Question" tool on Learn.
