### ISSUE TITLE
Unnecessary request to fork and submit a PR?

### ISSUE THREAD

**Issue by PeterBell** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#23]
When I went through this class, I was asked to fork and then submit a PR, even though there is nothing to really contribute:

<img width="1186" alt="screen shot 2016-03-07 at 10 46 14 am" src="https://cloud.githubusercontent.com/assets/4843/13574400/f030bf2a-e451-11e5-8c30-d4c8e504799b.png">

I don't immediately see where in this repo it defines whether you should be asked to fork/submit PR's, so not sure how to "fix" this or indeed if this is a bug.

**Comment by PeterBell** [comment]
Talking to myself. Replicated this is an issue. Have escalated to learn labs team to figure out how learn classifies this as needing a fork/PR workflow. Still pending. cc @AnnJohn just FYI

**Comment by PeterBell** [comment]
OK, found out what was up - this was marked as a lab in the Full Stack track (but not in the Intro to Ruby track). Have switched it in learn to a readme. Tested and working. Resolved :)

**Comment by AnnJohn** [comment]
thank you!
