### ISSUE TITLE
Instructions on how to complete lesson are unclear

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#27]
@Alicekb 

Should this lesson require a PR to be submitted? There are no instructions on how a student should proceed. 

The lesson is currently set up like a code-along, but the "solution" (the code written the video) is already there. So, as it is now, a student needs to randomly modify a file in order to submit a pull request so that the lesson shows as complete.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention, this lesson is now marked as a README.

As always thank you for contributing.

**Comment by kwebster2** [comment]
@curiositypaths 
Hey Jason, it looks like this issue is back with v5 of the full stack track. It is now a lab again.
