### ISSUE TITLE
Lesson is currently a lab; should be a README 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#31]
@curiositypaths @fi-curriculum-team 
This lesson is showing as a lab in v5 of the full stack track. It should be a README.

**Comment by DanielSeehausen** [comment]
the client facing feature to toggle readme/lab is temporarily disabled by the dev team. will reach out and see if this can't be fixed by someone internally until the feature is re-implemented.

**Comment by DanielSeehausen** [comment]
thank you for bringing this to our attention @kwebster2 @curiositypaths 

this is currently designated as a code along (we now have more than just readme/code-along -- new feature. if it is throwing some spec issue, please let me know. Code alongs resemble labs more than readmes).

**Comment by kwebster2** [comment]
Hey @DanielSeehausen ! If that is the case, then it is a bit confusing for students. The repo already has all of the code shown in the lesson, so if the student is following along with the video, they would not have to add anything. If they don't have to add anything, then they will not be able to submit a pull request (they would have to add some arbitrary code to force a pull request to work, which I don't think is a great experience so early in the program). In addition, there are no specific instructions letting the student know that they are expected to follow along, use the IDE, or submit anything at the end.

**Comment by DanielSeehausen** [comment]
This is an excellent point @kwebster2, and something your issue led us to raise with the product team and begin discussing. We are working on addressing it now. I am going to keep this issue closed for now as it is a larger issue with learn.co and not the lesson's content itself. Please stay tuned for a fix!

Thank you again.

**Comment by DanielSeehausen** [comment]
now a readme when deployed in the future @kwebster2 thank you again
