### ISSUE TITLE
Doesn't mark complete

### ISSUE THREAD

**Issue by sean-flanagan** [learn-co-curriculum/ruby-lecture-intro-what-is-a-program#33]
when one finishes, completes, hits next, still doesn't get a green check.

**Comment by sean-flanagan** [comment]
Still doesn't mark complete

**Comment by drakeltheryuujin** [comment]
Hi @sean-flanagan! 
This request sounds like a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
